language: objective-c

osx_image: xcode8.3

script:
  - xcodebuild clean && xcodebuild build -sdk iphonesimulator10.0 -project ios/ci sandbox/ci sandbox.xcodeproj -scheme ci sandboxTests CODE_SIGNING_REQUIRED=NO